Update and rename .gitignore to gitignore
Becky449/hello-microverse pull request #1
Opened 2022-08-17 12:31 UTC by Becky449

Updated and renamed .gitignore to gitignore

2022-08-17 13:43 UTC, Reem-lab requested changes
# Hi @Becky449, 👋🏻👋🏻

Good job so far!🔥🔥🚀🚀🚀
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Great working on the functionality✅
📌 Good commit messages ✅
📌 Professional README file. ✅

## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly make your PR more descriptive since I can see just one clause in your PR the importance of the description that you explain what you did in this specific milestone so please add more description with a descriptive title🚀💯💯🔥🔥

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 13:43 UTC, Reem-lab commented on .hintrc
> +}
- [ ] Great on set the linters but I think you didn't  install the backages for stylelint and hintrc If you scroll down a little bit you can find how to install the linters packages since the first command for set up and the second to fix the errors 💯💯
![image](https://user-images.githubusercontent.com/58553711/185010847-63e8a6ba-6926-48fb-b8b9-b19f5d7975c3.png)

2022-08-17 13:43 UTC, Reem-lab commented on README.md
> +hello-microverse project involves the use of linter to check code
- [ ] I suggest adding the `README` file to your project :ok_hand:, Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it :wink:
> And don't forget to add the `MIT.md` file as well 💯💯
> > The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. :100:
>

2022-08-18 09:43 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @Becky449 ✋

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="480" height="270" class="giphy-embed" />

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-18 09:48 UTC, merged